Add database
Bervy/java-filmorate pull request #12
Opened 2022-09-12 11:47 UTC by Bervy

2022-09-12 17:53 UTC, Frilock requested changes
Добрый день, оставил несколько комментариев к работе, постарался сделать их подробными. Вы в работе использовали много интересных идей, мне понравилось, но все таки часть комментариев нужно поправить. Жду новую итерацию.

2022-09-12 17:53 UTC, Frilock commented on pom.xml
>  			<artifactId>spring-boot-starter-web</artifactId>
Зачем trace файлы показывать при ревью? Добавьте весь пакет db в .gitignore файл, поскольку они не несут никакой информационной нагрузки

2022-09-12 17:53 UTC, Frilock commented on pom.xml
>              <groupId>org.aspectj</groupId>
Тогда и тут нужно форматирование поправить. Кстати, не знаю писал ли Вам до этого об этом или нет, но советую установить в IDEA плагин sonarlint. Это статический анализатор кода, подсветит потенциально опасные места и покажет ряд хороших практик при написании кода.

2022-09-12 17:53 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/impl/FilmController.java
> +public class FilmController implements AbstractController<Film> {
Кстати по поводу абстракций. Их тоже можно расширять. Вы можете сделать FindAbstractController, где будет 2 метода findAll и findById, от него заимплементировать те контроллеры в которых есть только 2 метода. Потом создать еще одну сущность AbstractController implements FindAbstractController куда добавить недостающие методы, и уже тут использовать именно его. Отсюда у Вас все контроллеры будут реализовывать какой то интерфейс. Но это не обязательное требование конечно. Просто как вариант

2022-09-12 17:53 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/mapper/FilmMapper.java
> +                releaseDate(resultSet.getDate("release_date").toLocalDate()).
Довольно распространённая проблема. Вы уверены что getDate не вернет null? Если да, то ок, иначе у Вас может быть тут NPE. Проверяйте что getDate вернул != null

2022-09-12 17:53 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/mapper/UserMapper.java
> +                .birthday(resultSet.getDate("birthday").toLocalDate())
Аналогично

2022-09-12 17:53 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +public class Genre {
equalsAndHashCode не нужен?

2022-09-12 17:53 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Rating.java
> +    public Rating(long id, String name) {
Можно заменить на AllArgsConstructor

2022-09-12 17:53 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Rating.java
> +public
Сьехало форматирование

2022-09-12 17:53 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @NotBlank @ContainsSpaces
Каждую аннотацию лучше на своей строке

2022-09-12 17:53 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/repository/impl/FilmImpl.java
> +        } catch (DataAccessException d) {
Лично на мой взгляд, все равно лучше называть исключения e

2022-09-12 17:53 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/repository/impl/FilmImpl.java
> +            throw new FilmorateNotFoundException(FILM_NOT_FOUND.getTitle());
Интересное решение с кодами для ошибок, мне понравилось, но все равно советую добавлять сообщение об ошибке, например, FILM_NOT_FOUND.getTitle() + ": " + e.getMessage();

2022-09-12 17:53 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/repository/impl/FilmImpl.java
> +        long filmId = simpleJdbcInsert.executeAndReturnKey(film.toMap()).longValue();
Тут 2 строчки можно в одну объединить

2022-09-12 17:53 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/repository/impl/FilmImpl.java
> +                    genresFromFrontEnd.removeAll(matchedGenres);
FrontEnd лучше просто на UI заменить =)

2022-09-12 17:53 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/repository/impl/GenreImpl.java
> +public class GenreImpl implements GenreDao {
Лучше назвать GenreRepositoryImpl, поскольку все таки речь идет именно о нем, а класс должен отображать суть

2022-09-12 17:53 UTC, Frilock commented on src/main/resources/data.sql
> +MERGE INTO PUBLIC.genre (genre_id, genre_name) VALUES ( 1, 'Комедия' );
По моему если схема PUBLIC, то ее можно явно не указывать

2022-09-13 05:26 UTC, Bervy commented on pom.xml
>  			<artifactId>spring-boot-starter-web</artifactId>
Поправил.

2022-09-13 05:28 UTC, Bervy commented on pom.xml
>              <groupId>org.aspectj</groupId>
Сонарлинтом пользуюсь) Интересно, что у меня в пом файле всё нормально отформатировано было.

2022-09-13 05:48 UTC, Bervy commented on src/main/java/ru/yandex/practicum/filmorate/controllers/impl/FilmController.java
> +public class FilmController implements AbstractController<Film> {
Реализовал.

2022-09-13 05:53 UTC, Bervy commented on src/main/java/ru/yandex/practicum/filmorate/mapper/FilmMapper.java
> +                releaseDate(resultSet.getDate("release_date").toLocalDate()).
Написал в слаке.

2022-09-13 05:53 UTC, Bervy commented on src/main/java/ru/yandex/practicum/filmorate/mapper/UserMapper.java
> +                .birthday(resultSet.getDate("birthday").toLocalDate())
Написал в слаке.

2022-09-13 06:06 UTC, Bervy commented on src/main/java/ru/yandex/practicum/filmorate/repository/impl/FilmImpl.java
> +            throw new FilmorateNotFoundException(FILM_NOT_FOUND.getTitle());
Добавил

2022-09-13 06:07 UTC, Bervy commented on src/main/java/ru/yandex/practicum/filmorate/repository/impl/FilmImpl.java
> +        long filmId = simpleJdbcInsert.executeAndReturnKey(film.toMap()).longValue();
Объединил.

2022-09-13 06:09 UTC, Bervy commented on src/main/java/ru/yandex/practicum/filmorate/repository/impl/FilmImpl.java
> +                    genresFromFrontEnd.removeAll(matchedGenres);
Заменил)

2022-09-13 06:14 UTC, Bervy commented on src/main/resources/data.sql
> +MERGE INTO PUBLIC.genre (genre_id, genre_name) VALUES ( 1, 'Комедия' );
Поправил.

2022-09-13 06:14 UTC, Bervy commented on src/main/java/ru/yandex/practicum/filmorate/repository/impl/GenreImpl.java
> +public class GenreImpl implements GenreDao {
Изменил названия

2022-09-13 06:37 UTC, Bervy commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +public class Genre {
Добавил

2022-09-13 06:37 UTC, Bervy commented on src/main/java/ru/yandex/practicum/filmorate/model/Rating.java
> +    public Rating(long id, String name) {
Заменил

2022-09-13 06:38 UTC, Bervy commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @NotBlank @ContainsSpaces
Поправил

2022-09-13 06:38 UTC, Bervy commented on src/main/java/ru/yandex/practicum/filmorate/repository/impl/FilmImpl.java
> +        } catch (DataAccessException d) {
Хорошо, поправил.

2022-09-13 09:49 UTC, Frilock approved these changes
Принято

2022-09-13 09:53 UTC, merged