10 спринт 1 ревью
Bervy/java-filmorate pull request #2
Opened 2022-08-15 19:26 UTC by Bervy

10 спринт 1 ревью

2022-08-15 19:54 UTC, Frilock requested changes
Добрый вечер, комментарии в коде. Жду новую итерацию работы)

2022-08-15 19:54 UTC, Frilock commented on pom.xml
> +            <version>1.9.7</version>
Не написал при прошлом ревью:  Версии библиотек, которые вы подключаете в pom файле, правильнее писать в preporties (по аналогии с версией java), поскольку pom файлы могут быть очень большого размера и изменение версии библиотеки может оказаться не такой простой задачей.

2022-08-15 19:54 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/ErrorResponse.java
> +public class ErrorResponse {
А зачем вам такой класс с одним полем? В чем смысл хранить туже самую строчку, но в обертке?

2022-08-15 19:54 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/CountFilmException.java
> +    public CountFilmException(String message) {
А зачем под каждую ситуацию свое исключение создавать?) Я конечно не особо против, просто интересно Ваше мнение

2022-08-15 19:54 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    FilmService filmService;
Модификатор?

2022-08-15 19:54 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    FilmStorage filmStorage;
Модификатор?

2022-08-15 19:54 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    public FilmStorage getFilmStorage() {
Так не делают. Если Вам где то нужен спринговый бин, инжектите его через Autowired

2022-08-15 19:54 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +    UserStorage userStorage;
Модификатор? Чего это Вы их ставить перестали?

2022-08-15 19:54 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +    @Autowired()
() не нужны

2022-08-15 19:54 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +    public void setUserStorage(UserStorage userStorage) {
Вообще это "холевар", но лично я предпочитаю, когда сеттеры идут в начале класса, то есть сразу после перечисления полей

2022-08-15 19:54 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +    Map<Long, Film> getFilms();
А зачем такая структура? Почему просто лист не вернуть?

2022-08-15 19:54 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +    Film getFilm(Long filmId);
На мой взгляд, лучше обозвать метод getFilmById, или findFilmById

2022-08-15 19:54 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/error/ErrorHandler.java
> +        return new ErrorResponse(
в 1 строчку не помещается?

2022-08-15 19:54 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/error/ErrorHandler.java
> +        return new ErrorResponse(
Влезает в 1 строчку, зачем в 3 писать?)

2022-08-15 19:54 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
>  public class UserController {
На самом деле у контроллеров много общего, можете как задачу со звездочкой попробовать сделать абстрактный контроллер, а эти от него унаследовать. Но это так, на Ваше усмотрение

2022-08-16 08:49 UTC, Bervy commented
10 спринт 2 ревью

2022-08-16 11:07 UTC, Bervy commented
10 спринт 2 ревью

2022-08-16 11:27 UTC, Bervy commented
10 спринт 2 ревью

2022-08-16 18:40 UTC, Frilock requested changes
Еще пара комментариев. Не спешите

2022-08-16 18:40 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
>  package ru.yandex.practicum.filmorate.controllers;
Чисто совет из своей последней практики. Вот у Вас сейчас в 1 пул реквест идет 20 коммитов. Я думаю, что лучше их объединить (прочитайте про squash коммитов). Чтобы в пул реквест шел 1 коммит. Это обычно делают для того, чтобы было проще откатывать изменения из мастер ветки если что то пошло не так. Неплохой получите навык по работе с гитом.
Но я не настаиваю, можете просто поразбираться

2022-08-16 18:40 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/AbstractController.java
> +    public abstract List<T> findAll();
Вы по сути тут только объявили сигнатуру методов (как в интерфейсе), но на деле вы можете и реализацию тут сделать

2022-08-16 18:40 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        return filmService.getFilmStorage().findAll();
Я уже писал, что так не делают. В FilmService делайте метод findAll, а внутри него делаете filmStorage.findAll()

2022-08-16 18:40 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        return filmService.getFilmStorage().create(film);
аналогично к другим методам

2022-08-16 18:40 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    @Autowired()
Не нужны скобки ()

2022-08-17 18:13 UTC, Frilock approved these changes
Принято

2022-08-17 18:13 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ExceptionDescriptions.java
> +    ExceptionDescriptions(String title) {
public

2022-08-19 13:27 UTC, merged